name: Create Linux VM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Create Linux VM
      - name: Create Linux VM
        run: |
          az vm create \
            --resource-group myResourceGroup \
            --name myLinuxVM \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --generate-ssh-keys \
            --size Standard_B1s
